server:
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: il8n.messages

mybatis-plus:
  type-aliases-package: com.nft.dao.entity
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      update-strategy: not_null
      insert-strategy: not_null
      id-type: Auto
      table-prefix: ts_
      logic-delete-value: 0
      logic-not-delete-value: 1
    configuration:
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true